//Layout
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE';
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE';

// empleados
export const LANZAR_MENSAJE_TOAST = 'LANZAR_MENSAJE_TOAST';
export const OBTENER_DATOS = 'OBTENER_DATOS';
export const MODIFICAR_INPUTS = 'MODIFICAR_INPUTS';

// Registro
export const MODIFICAR_INPUTS_REGISTRO = 'MODIFICAR_INPUTS_REGISTRO';
