//Layout
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE';
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE';

// empleados
export const MODIFICAR_INPUTS_BUSQUEDA = 'MODIFICAR_INPUTS_BUSQUEDA';
export const OBTENER_EMPLEADOS = 'OBTENER_EMPLEADOS';

// Registro
export const MODIFICAR_INPUTS_REGISTRO = 'MODIFICAR_INPUTS_REGISTRO';
export const REGISTRO_REALIZADO = 'REGISTRO_REALIZADO';
export const OBTENER_PAISES = 'OBTENER_PAISES';
export const OBTENER_TIPO_IDENTIFICACIONES = 'OBTENER_TIPO_IDENTIFICACIONES';
export const OBTENER_CORREOS_SIMILARES = 'OBTENER_CORREOS_SIMILARES';
